controller:
  image:
    repository: ghcr.io/zapier/prom-aggregation-gateway
    tag: latest

  apiPort: 8080
  lifecyclePort: 8888

  replicaCount: 1

  type: Deployment

  env:
    GIN_MODE: release

podMonitor:
  create: true

service:
  create: true
  annotations: {}
  type: LoadBalancer
  port: 8080
  nodePort: 12345

serviceMonitor:
  create: true
