name: pr_build
on:
  pull_request:
    paths:
      - '*'
      - '*/**'
      - '!README.md'
      - '!.tool-versions'
      - '!COPYING.LGPL-3'
      - '!.gitattributes'
      - '!.gitignore'


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.6.30

      - uses: actions/checkout@v3

      - run: earthly +build

  skaffold:
    runs-on: ubuntu-22.04
    steps:
      - uses: earthly/actions-setup@v1
        with: { version: v0.6.30 }

      - uses: actions/checkout@v3

      - name: start minikube
        uses: hiberbee/github-action-minikube@1.5.0

      - name: setup helm
        uses: hiberbee/github-action-helm@1.3.0

      - name: run skaffold
        uses: hiberbee/github-action-skaffold@1.20.0
        with:
          command: run
