name: release new version

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.6.30

      - name: checkout the source code
        uses: actions/checkout@v3

      - name: Extract tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        run: |
          earthly \
            --push \
            +release \
            --version=${{ env.RELEASE_VERSION }} \
            --image_name=ghcr.io/${{ github.repository_owner }}/prom-aggregation-gateway \
            --token ${{ secrets.GITHUB_TOKEN }}
